AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 Action Slack Notifier

Parameters:
  SlackUrl:
    AllowedPattern : ".+"
    Type: String

Resources:
  S3ActionNotifierLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 10
      CodeUri: ./target/lambda.zip
      Environment:
        Variables:
          SLACK_WEBHOOK_URI:
            Ref: SlackUrl
